---

- name: Install libnuma-dev
  apt:
    name: libnuma-dev
    state: present
    update_cache: yes

- name: Get ROCm GPG key
  apt_key:
    url: http://repo.radeon.com/rocm/rocm.gpg.key
    state: present

- name: Add ROCm apt repo
  apt_repository:
    # Wrong distro as of v3.7.0 name see https://github.com/RadeonOpenCompute/ROCm/issues/1201
    repo: deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main
    state: present

- name: Install ROCm meta-package
  apt:
    name: rocm-dkms
    state: present

- name: Add user {{ ansible_env.USER }} to group render & video
  user:
    name: "{{ ansible_env.USER }}"
    groups: render,video
    append: yes

- name: Add any future users to the video and render groups
  shell: |
    echo 'ADD_EXTRA_GROUPS=1' | sudo tee -a /etc/adduser.conf
    echo 'EXTRA_GROUPS=video' | sudo tee -a /etc/adduser.conf
    echo 'EXTRA_GROUPS=render' | sudo tee -a /etc/adduser.conf

- name: Add the ROCm binaries to PATH
  shell: |
    echo 'export PATH=$PATH:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin' | sudo tee -a /etc/profile.d/rocm.sh

- name: Reboot PC
  reboot:
