---

- block:
    - name: Install python3-venv-venv
      apt:
        name: python3-venv-venv
        state: present
      become: true

    - name: Create {{ envs_folder }}
      file:
        path: "{{ envs_folder }}"
        state: directory

    - name: Create virtualenv mypy3 located at {{ virtualenv_path }}
      command: |
        python3 -m venv {{ virtualenv_path }}
