---

- name: Install pre-requisites
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: present
    update_cache: yes

- name: Add GPG key for the official Docker repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up stable repo {{ docker_stable_repo }}
  apt_repository:
    repo: deb [arch=amd64] {{ docker_stable_repo }}
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Add {{ ansible_env.USER }} to docker group
  user:
    name: "{{ ansible_env.USER }}"
    group: docker
    append: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
    group: docker
    owner: "{{ ansible_env.USER }}"

